const influencer = [
    {
      profilePicture: "assets/pictures/saschafirtina.jpg",
      username: "saschafirtina",
      name: "Sascha Firtina",
      biography: "ENTREPRENEUR..  🥇 working on the next big thing, 🏝 traveling the world, ☀️ Happiness is the key! ☀️ 📍Berlin",
      followers: 13838,
      following: 361,
      userId: 1533777427,
      numPosts: 149,
      website: "",
      lastPost: "09/08/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/marin.ivankovic.jpg",
      username: "marin.ivankovic",
      name: "Marin",
      biography: "Just a guy, who decided to go for it — 📍 🇭🇷 living in Berlin 🇩🇪 🚀 Startups | Fashion | Fitness 👻 Snapchat: mrn_kovic",
      followers: 26561,
      following: 454,
      userId: 274836879,
      numPosts: 808,
      website: "",
      lastPost: "01/09/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/bluemaex.jpg",
      username: "bluemaex",
      name: "Max",
      biography: "Berlin and the rest of the world. iPhone only.",
      followers: 261,
      following: 229,
      userId: 34943228632,
      numPosts: 1308,
      website: "",
      lastPost: "29/08/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/kanyewest.jpg",
      username: "kanyewest",
      name: "ye",
      biography: "",
      followers: 3984285,
      following: 1,
      userId: 3949224551,
      numPosts: 188,
      website: "",
      lastPost: "04/10/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/jxhannamadeleine.jpg",
      username: "jxhannamadeleine",
      name: "𝐉𝐎𝐇𝐀𝐍𝐍𝐀 𝐊𝐎𝐌𝐈𝐍𝐄𝐊 🌹",
      biography: "• german/czechia • '94 •📍frankfurt • • 👻 msmoootley • 📚 student • ❥ sponsored by ironmaxx •",
      followers: 81458,
      following: 555,
      isPrivate: "",
      userId: 226675238,
      pk: 226675238,
      numPosts: 247,
      website: "",
      lastPost: "02/10/2018",
      engagement: 3205.25,
      engagementScore: 3.93,
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/beyonce.jpg",
      username: "beyonce",
      name: "Beyoncé",
      biography: "",
      followers: 118448693,
      following: 0,
      userId: 247944034,
      numPosts: 1679,
      website: "http://www.BEYONCE.com/",
      lastPost: "03/10/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/chapteronecoffeeberlin.jpg",
      username: "nanokaffeeberlin",
      name: "nano kaffee berlin",
      biography: "kaffeebar | beans | utensils  specialty coffee in Berlin Kreuzberg |  Mo - Fr 8.30 - 18.00 Sat 12.00 - 17.00 Sun closed",
      followers: 4315,
      following: 892,
      userId: 1537710537,
      numPosts: 640,
      website: "http://www.nano-kaffee.de/shop",
      lastPost: "06/09/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/chapteronecoffeeberlin.jpg",
      username: "chapteronecoffeeberlin",
      name: "Chapter One Coffee Berlin",
      biography: "Mittenwalder Str.30, 10961 Berlin, mo-sa: 9.00-18.00/so: 11.00-18.00",
      followers: 2731,
      following: 1199,
      isPrivate: "",
      userId: 1534537685,
      numPosts: 321,
      website: "http://www.chapter-one-coffee.com/",
      lastPost: "11/09/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/saschafirtina.jpg",
      username: "saschafirtina-copy",
      name: "Sascha Firtina",
      biography: "ENTREPRENEUR..  🥇 working on the next big thing, 🏝 traveling the world, ☀️ Happiness is the key! ☀️ 📍Berlin",
      followers: 13838,
      following: 361,
      userId: 15337774264,
      numPosts: 149,
      website: "",
      lastPost: "09/08/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/marin.ivankovic.jpg",
      username: "marin.ivankovic-copy",
      name: "Marin",
      biography: "Just a guy, who decided to go for it — 📍 🇭🇷 living in Berlin 🇩🇪 🚀 Startups | Fashion | Fitness 👻 Snapchat: mrn_kovic",
      followers: 26561,
      following: 454,
      userId: 274836842679,
      numPosts: 808,
      website: "",
      lastPost: "01/09/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/bluemaex.jpg",
      username: "bluemaex-copy",
      name: "Max",
      biography: "Berlin and the rest of the world. iPhone only.",
      followers: 261,
      following: 229,
      userId: 349432228532,
      numPosts: 1308,
      website: "",
      lastPost: "29/08/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/kanyewest.jpg",
      username: "kanyewest-copy",
      name: "ye",
      biography: "",
      followers: 3984285,
      following: 1,
      userId: 39492245510,
      numPosts: 188,
      website: "",
      lastPost: "04/10/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/jxhannamadeleine.jpg",
      username: "jxhannamadeleine-copy",
      name: "𝐉𝐎𝐇𝐀𝐍𝐍𝐀 𝐊𝐎𝐌𝐈𝐍𝐄𝐊 🌹",
      biography: "• german/czechia • '94 •📍frankfurt • • 👻 msmoootley • 📚 student • ❥ sponsored by ironmaxx •",
      followers: 81458,
      following: 555,
      isPrivate: "",
      userId: 2266752380,
      pk: 226675238,
      numPosts: 247,
      website: "",
      lastPost: "02/10/2018",
      engagement: 3205.25,
      engagementScore: 3.93,
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/beyonce.jpg",
      username: "beyonce-copy",
      name: "Beyoncé",
      biography: "",
      followers: 118448693,
      following: 0,
      userId: 2479440340,
      numPosts: 1679,
      website: "http://www.BEYONCE.com/",
      lastPost: "03/10/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/chapteronecoffeeberlin.jpg",
      username: "nanokaffeeberlin",
      name: "nano kaffee berlin",
      biography: "kaffeebar | beans | utensils  specialty coffee in Berlin Kreuzberg |  Mo - Fr 8.30 - 18.00 Sat 12.00 - 17.00 Sun closed",
      followers: 4315,
      following: 892,
      userId: 15377105370,
      numPosts: 640,
      website: "http://www.nano-kaffee.de/shop",
      lastPost: "06/09/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/chapteronecoffeeberlin.jpg",
      username: "chapteronecoffeeberlin-copy",
      name: "Chapter One Coffee Berlin",
      biography: "Mittenwalder Str.30, 10961 Berlin, mo-sa: 9.00-18.00/so: 11.00-18.00",
      followers: 2731,
      following: 1199,
      isPrivate: "",
      userId: 15345376850,
      numPosts: 321,
      website: "http://www.chapter-one-coffee.com/",
      lastPost: "11/09/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/saschafirtina.jpg",
      username: "saschafirtina-copy2",
      name: "Sascha Firtina",
      biography: "ENTREPRENEUR..  🥇 working on the next big thing, 🏝 traveling the world, ☀️ Happiness is the key! ☀️ 📍Berlin",
      followers: 13838,
      following: 361,
      userId: 15337774847,
      numPosts: 149,
      website: "",
      lastPost: "09/08/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/marin.ivankovic.jpg",
      username: "marin.ivankovic-copy2",
      name: "Marin",
      biography: "Just a guy, who decided to go for it — 📍 🇭🇷 living in Berlin 🇩🇪 🚀 Startups | Fashion | Fitness 👻 Snapchat: mrn_kovic",
      followers: 26561,
      following: 454,
      userId: 2784574836879,
      numPosts: 808,
      website: "",
      lastPost: "01/09/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/bluemaex.jpg",
      username: "bluemaex-copy2",
      name: "Max",
      biography: "Berlin and the rest of the world. iPhone only.",
      followers: 261,
      following: 229,
      userId: 3494322226,
      numPosts: 1308,
      website: "",
      lastPost: "29/08/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/kanyewest.jpg",
      username: "kanyewest-copy2",
      name: "ye",
      biography: "",
      followers: 3984285,
      following: 1,
      userId: 394922455102,
      numPosts: 188,
      website: "",
      lastPost: "04/10/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/jxhannamadeleine.jpg",
      username: "jxhannamadeleine-copy2",
      name: "𝐉𝐎𝐇𝐀𝐍𝐍𝐀 𝐊𝐎𝐌𝐈𝐍𝐄𝐊 🌹",
      biography: "• german/czechia • '94 •📍frankfurt • • 👻 msmoootley • 📚 student • ❥ sponsored by ironmaxx •",
      followers: 81458,
      following: 555,
      isPrivate: "",
      userId: 22667523802,
      pk: 226675238,
      numPosts: 247,
      website: "",
      lastPost: "02/10/2018",
      engagement: 3205.25,
      engagementScore: 3.93,
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/beyonce.jpg",
      username: "beyonce-copy2",
      name: "Beyoncé",
      biography: "",
      followers: 118448693,
      following: 0,
      userId: 24794403402,
      numPosts: 1679,
      website: "http://www.BEYONCE.com/",
      lastPost: "03/10/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/chapteronecoffeeberlin.jpg",
      username: "nanokaffeeberlin-copy2",
      name: "nano kaffee berlin",
      biography: "kaffeebar | beans | utensils  specialty coffee in Berlin Kreuzberg |  Mo - Fr 8.30 - 18.00 Sat 12.00 - 17.00 Sun closed",
      followers: 4315,
      following: 892,
      userId: 153771053702,
      numPosts: 640,
      website: "http://www.nano-kaffee.de/shop",
      lastPost: "06/09/2018",
      email: "No email in bio"
    },
    {
      profilePicture: "assets/pictures/chapteronecoffeeberlin.jpg",
      username: "chapteronecoffeeberlin-copy2",
      name: "Chapter One Coffee Berlin",
      biography: "Mittenwalder Str.30, 10961 Berlin, mo-sa: 9.00-18.00/so: 11.00-18.00",
      followers: 2731,
      following: 1199,
      isPrivate: "",
      userId: 153453768520,
      numPosts: 321,
      website: "http://www.chapter-one-coffee.com/",
      lastPost: "11/09/2018",
      email: "No email in bio"
    }
]
export default influencer;